### ISSUE TITLE
[Makefile:217285: dlls/winex11.drv/mouse.o] Error 1

### ISSUE THREAD

**Issue by vivantart** [Kron4ek/wine-tkg#3]
Hi! I can't successfully compile the 9.4 version, but I have been compiling successfully since 9.1. I have xorg-dev and all necessary dependencies.
Here's the console output: 

dlls/winex11.drv/mouse.c: In function ‘map_raw_event_coords’:
dlls/winex11.drv/mouse.c:1788:84: error: ‘UINT16_MAX’ undeclared (first use in this function)
 1788 |     if (input->mi.dwFlags & MOUSEEVENTF_VIRTUALDESK) SetRect( &virtual_rect, 0, 0, UINT16_MAX, UINT16_MAX );
      |                                                                                    ^~~~~~~~~~
dlls/winex11.drv/mouse.c:60:1: note: ‘UINT16_MAX’ is defined in header ‘<stdint.h>’; did you forget to ‘#include <stdint.h>’?
   59 | #include "wine/debug.h"
  +++ |+#include <stdint.h>
   60 | 
dlls/winex11.drv/mouse.c:1788:84: note: each undeclared identifier is reported only once for each function it appears in
 1788 |     if (input->mi.dwFlags & MOUSEEVENTF_VIRTUALDESK) SetRect( &virtual_rect, 0, 0, UINT16_MAX, UINT16_MAX );
      |                                                                                    ^~~~~~~~~~
make: *** [Makefile:217285: dlls/winex11.drv/mouse.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by Kron4ek** [comment]
Hi, you need to compile from this commit https://github.com/Kron4ek/wine-tkg/commit/471bb366bfe729d6090a337835cf1c9ede1f5921.

**Comment by vivantart** [comment]
Oh! Thank you! I'll try it now.
