### ISSUE TITLE
EA game activation hasn't worked since 9.5

### ISSUE THREAD

**Issue by mikeserv-git** [Kron4ek/wine-tkg#4]
I have been using this project (wine-tkg/Kron4ek) for my system wine for some time now. I'm not sure who, what or why but I haven't been able to use it since the Wine 9.5 checkout because no EA games will launch, because of ActivationUI.exe. It just hangs in the process list and games won't launch. (these games are already activated, this is just the authoritarian activation CHECK)

With current 9.9 sources, the problem remains.

I can go back to my already built wine-tkg-Kron4ek 9.5 package, (or recompile it and it's still fine) and EA's ActivationUI.exe works correctly.

As this is my system wine, everything I need it for has to work (and the EA Mass Effect and Star Wars games are probably the most important user of it for me, at that). I use proton-tkg for Steam, but these sources for everything non-steam.

I'm guessing it's probably upstream (If I built THAT, I wouldn't be getting that far to play these EA games in the first place with it, so I can't really test), but...

Anybody else notice this or have any kind of idea what the problem with it could be?

**Comment by Kron4ek** [comment]
Starting from 9.6 there is no childwindow-proton.patch applied, maybe this is the reason, or maybe just a regression in upstream.

To know if the reason is indeed in childwindow-proton, you can compile from [this](https://github.com/Kron4ek/wine-tkg/tree/test) branch (it's 9.5 without childwindow-proton.patch applied).

**Comment by mikeserv-git** [comment]
Thank you very much for the suggestion. It doesn't seem related to the childwindow proton patch.

I checked out 92eddf7f846afe23560ff419487bff58982a3a97 and built it and the EA ActivationUI.exe still works correctly with that build.

So it must be upstream.

**Comment by mikeserv-git** [comment]
Good news, this seems to be fixed in 9.14. The EA ActivationUI.exe works for me again. It didn't in subsequent versions up to 9.13 and I almost wasn't going to bother trying this one, but I was pleasantly surprised.

Since this was almost certainly something upstream, and it seems fixed now, I'll close it.
